version: '3.4'

services:
  frontendservice:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: frontend
    build:
      context: .
      dockerfile: ../Frontend/Dockerfile

  computenodeservice:
    image: ${DOCKER_REGISTRY-}computenode
    container_name: computenode
    build:
      context: .
      dockerfile: ../ComputeNode/Dockerfile