version: '3.4'

services:
  frontendservice:
    image: ${DOCKER_REGISTRY-}controlnode
    container_name: controlnode
    build:
      context: .
      dockerfile: ../ControlNode/Dockerfile

  computenodeservice:
    image: ${DOCKER_REGISTRY-}computenode
    container_name: computenode
    build:
      context: .
      dockerfile: ../ComputeNode/Dockerfile