using AutoGeneratedComputeNodeClient;
using Frontend.Data;
using Frontend.Models;
using Frontend.Topology;
using Microsoft.EntityFrameworkCore;

namespace Frontend.Engine
{
    public class DistributedScheduler : IScheduler
    {
        private readonly ILogger<DistributedScheduler> _logger;
        private IDbContextFactory<JobContext> _contextFactory;
        private readonly IAddressManager _toplogyManager;
        private readonly Dictionary<int, Job> inProgressTasks = new Dictionary<int, Job>();

        public DistributedScheduler(
            ILogger<DistributedScheduler> logger,
            //IDbContextFactory<JobContext> _contextFactory,
            IAddressManager toplogyManager)
        {
            this._logger = logger;
            //this._contextFactory = context;
            this._toplogyManager = toplogyManager;
        }

        public static void Initialize(string connectionString)
        {
            Console.WriteLine("Starting distributed scheduler...");
        }

        public async Task ScheduleJobAsync(Job job)
        {
            try
            {
                // Create tasks for atomic units of execution
                string[] unitsOfWork = job.Data.Split(';');

                // NOT DONE:
                // [ADVANCED] use custom routing to available ComputeNodes using ingress setup

                // Create compute node client
                string computeNodeServiceAddress = _toplogyManager.ComputeNodeServiceAddress;
                var httpClient = new HttpClient();
                var computeNodeClient = new ComputeNodeClient(computeNodeServiceAddress, httpClient);

                // Send units of execution to compute nodes
                var result = new List<AtomicJobResult>();
                int i = 0;
                foreach (string unit in unitsOfWork)
                {
                    i++;
                    var r = await computeNodeClient.RunAsync(i, job.Id, unit);
                    result.Add(r);
                    _logger.LogInformation($"JobId {i}; AtomicJobId {job.Id}; ResultState: {r.State}; Result {r.Result}; Error {r.Error}");
                }

                // Monitor the execution
                // TODO
                _logger.LogInformation($"Scheduled job with id {job.Id}");

                // TODO
                inProgressTasks.Add(job.Id, job);
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"Failed to schedule job with id {job.Id}");
            }
        }
    }
}
