apiVersion: apps/v1
kind: Deployment
metadata:
  name: computenode
  namespace: distributed-system-dev-ns
  labels:
    app: computenode
spec:
  replicas: 5
  selector:
    matchLabels:
      service: computenode
  template:
    metadata:
      labels:
        app: computenode
        service: computenode
    spec:
      containers:
        - name: computenode
          image: matfmastercr.azurecr.io/computenode:v5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: computenode
  namespace: distributed-system-dev-ns
  labels:
    app: computenode
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: computenode
  internalTrafficPolicy: Local