apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-computenode
  namespace: distributed-system-dev-ns
  labels:
    app: computenodeservice
spec:
  replicas: 2
  selector:
    matchLabels:
      service: computenode-pod
  template:
    metadata:
      labels:
        app: computenode-pod
        service: computenode-pod
    spec:
      containers:
        - name: computenodeservice-container
          image: matfmastercr.azurecr.io/computenode:v2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
---
apiVersion: v1
kind: Service
metadata:
  name: computenode-service
  namespace: distributed-system-dev-ns
  labels:
    app: computenode
    service: computenode
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: port80
      targetPort: 80
      protocol: TCP
    - port: 443
      name: port443
      targetPort: 443
      protocol: TCP
  selector:
    service: computenode-pod